### ISSUE TITLE
Add account linking support

### ISSUE THREAD

**Issue by nkshah2** [supertokens/dashboard#108]
This issue is meant to review the implementation of account linking support in the user management dashboard

**Comment by nkshah2** [comment]
- [ ] Auth screen spacing button button is wrong

![Screenshot 2023-08-22 at 11 05 21 AM](https://github.com/supertokens/dashboard/assets/18233774/05943720-808a-4954-af36-70fa579ed525)

- [ ] User info is not responsive

<img width="599" alt="Screenshot 2023-08-22 at 2 49 39 PM" src="https://github.com/supertokens/dashboard/assets/18233774/be774de0-d764-4b85-8342-b658a5a8a209">

<img width="584" alt="Screenshot 2023-08-22 at 2 50 10 PM" src="https://github.com/supertokens/dashboard/assets/18233774/4fbab0c2-3211-4ee5-aeb0-ecd15a2f6428">

**Comment by iresharma** [comment]
## Pending TODO
- Email verify spacing issues

**Comment by iresharma** [comment]
- [ ] Email unverify gives right response but on save it changes back to verified
