### ISSUE TITLE
Dashboard Visibility and Usage Issue: "You need to enable JavaScript to run this app."

### ISSUE THREAD

**Issue by Mohit-Hurkat** [supertokens/dashboard#149]
**Description**:

I am operating a User Management Dashboard on a self-hosted service and experiencing issues with its visibility and usage. The dashboard intermittently displays an error message stating, "You need to enable JavaScript to run this app," even though JavaScript is enabled in the browser.

**Current Configuration:**

```
recipe_list = [
    dashboard.init(
        admins=[
            settings.supertoken_admin_dashboard_email,
        ],
    ),
    session.init(),
    passwordless.init(
        flow_type="USER_INPUT_CODE",
        contact_config=ContactPhoneOnlyConfig()
    )
]
```

**Issue**:

The dashboard works sometimes but occasionally fails with the aforementioned error message. This inconsistency affects the dashboard accessibility.

<img width="1502" alt="super_token_dashboard_blank" src="https://github.com/user-attachments/assets/2ae96f8c-bd86-4300-86c4-39411c659cb3">

**Expected Behavior:**
The dashboard should consistently function without displaying the "You need to enable JavaScript to run this app." error message, given that JavaScript is enabled in the browser.

**Environment:**
Self-hosted service
JavaScript enabled in the browser

**Request:**
Please advise if any modifications to the recipe_list configuration are required to ensure the dashboard operates correctly across all cases and browsers. Any guidance on resolving this issue would be greatly appreciated.

**Additional Context:**
If there are specific logs or additional information needed, please let me know, and I will provide them promptly.

Thank you for your assistance.

**Comment by rishabhpoddar** [comment]
Im not sure if this is a supertokens related issue, but can you show the browser console?

**Comment by Mohit-Hurkat** [comment]
Getting quirks mode Issue 

<img width="1214" alt="quirks_mode_issue" src="https://github.com/user-attachments/assets/04a762ac-d8aa-44a3-935a-4c7708680529">


_**Page lacks the HTML doctype, thus triggering quirks mode**_

**Comment by rishabhpoddar** [comment]
Hey @Mohit-Hurkat , sorry, we haven't had time to look into this. Not sure when we will be able to, but we will try soon.

**Comment by Mohit-Hurkat** [comment]
@rishabhpoddar  Any update on this one ?? Still ain't able to open the Dashboard using the mentioned configuration within the setup steps..

**Comment by ohansFavour** [comment]
Hi @Mohit-Hurkat,

We’ve reviewed your issue but couldn’t reproduce it on our end. Additionally, we haven’t received similar reports from other users. Given this, we’ll be closing the issue for now.

If you’re able to provide more details or a reproducible example, please feel free to reopen it. We’ll be happy to investigate further!

Thank you for your understanding.
