### ISSUE TITLE
Changes required before initial release

### ISSUE THREAD

**Issue by nkshah2** [supertokens/dashboard#16]
- [x] The auth screen needs to be redesigned and reimplemented
- [x] Remove the country flag icon from the list item (@sulha199 )
- [x] Some colors and styles are not as per the designs, double check all styling and make sure they conform to the designs (@sulha199 )
- [x] There does not need to be a separate route for the auth screen, the auth wrapper can display the form if auth is required
- [x] In the empty state for the users list, also mention that when using supertokens with only the session recipe the user list will be empty (@sulha199 )
- [x] The list should be mobile friendly, we can have the UI be scrollable to the right and truncate fields if needed (@sulha199 )
- [x] Rename "User Info" column name to "User"
- [x] Unknown routes (/haha for example) should default to the "/" route
- [x] Add error boundary to the react app, also handle network and other errors
- [x] We need to add some supertokens branding to the dashboard, this needs to be designed
- [x] Add the copyright header to all files

**Comment by nkshah2** [comment]
- [ ] Auth screen needs to be redesigned - add more content, make it look more fancy + professional, ST logo needs to be in the center (inside the form or outside) @mufassirkazi 
- [ ] User table should mention connection uri, it should be made clear if they are using try.supertokens.com @mufassirkazi 

- [ ] Footer for non auth screens can be sticky @nkshah2 
- [ ] Column content (titles and content) need to be center aligned [Maybe only auth method needs this, need to decide] @nkshah2 
- [ ] When refreshing the page the error state shows up for a second before the loading state @nkshah2 

- [ ] Time joined should mention the year (only if the date joined is within the last 365 days)
- [ ] For the users column, spacing between the text is incorrect
- [ ] In mobile view, the content above the table needs to be responsive properly the table should be the only thing that scrolls. The rest of the content should properly be sized inside of the viewport 
- [ ] All content should be fully responsive
- [ ] Use the error state colors from the designs for user table error states and not auth form
- [ ] The user count should follow proper comma convention for large numbers
- [ ] The phone number is not formatted properly, spacing is improper when the area code is 3 digits
- [ ] Really long emails break the UI
- [ ] Really long Names
- [ ] For only a single page of users, the pagination should be disabled
- [ ] Logo in the footer is not correctly sized
- [ ] Add 40px worth of top spacing above the icon at the top of the users table page
- [ ] Icon in the top should be 35x32px
- [ ] Third party pill has incorrect padding, remove line height
- [ ] Empty state styling is off, the 3rd line of text feels out of place, it should use proper spacing

**Comment by sulha199** [comment]
> The phone number is not formatted properly, spacing is improper when the area code is 3 digits

This is because some email field contains phone number, just like the data below

![image](https://user-images.githubusercontent.com/13642906/184356724-9c13d4c3-7d5f-4315-8a41-de0358be1b29.png)

**Comment by nkshah2** [comment]
Closing since all tasks in this list are resolved
