### ISSUE TITLE
Allow manual creation of users via dashbaord

### ISSUE THREAD

**Issue by rishabhpoddar** [supertokens/dashboard#44]

**Comment by Saxenaa218** [comment]
@rishabhpoddar is that issue still open, i'm new here and wanna contribute

**Comment by Chakravarthy7102** [comment]
-[ ] Add a warning that custom overrides for the sign up recipe function on the backend will be run when a user is created, however, the sign up API override will not run, and for more info, link to the docs on a page that talks about this.

- [ ] Post creation of the user, open a new tab to created new user details
