### ISSUE TITLE
Search Users

### ISSUE THREAD

**Issue by DarkPhoenix2704** [supertokens/dashboard#67]
Search users by email/phone

**Comment by DarkPhoenix2704** [comment]
@rishabhpoddar  i would like to work on this issue

- Create an Api for Search in [Supertokens Core ](https://github.com/supertokens/supertokens-core/blob/master/src/main/java/io/supertokens/webserver/api/core/)  - [ ]
- Update the ui - [ ]

**Comment by rishabhpoddar** [comment]
hey @DarkPhoenix2704 sure. I have a try at it :)

One change i would recommend is that instead of just adding the `search` query param, we should also add a `type` query param like:
```
search=xyz&type=phone
```

or 
```
search=xyz&type=email
```

**Comment by DarkPhoenix2704** [comment]
> One change i would recommend is that instead of just adding the `search` query param, we should also add a `type` query param like:
> 
> ```
> search=xyz&type=phone
> ```
> 
> or
> 
> ```
> search=xyz&type=email
> ```

But adding type query param makes user select whether they want to search by email or phone. 
If I have a list of users to search with mixed email & phone, it will be difficult to switch the search options

We can implement something like this
![Screenshot 2023-01-31 182915](https://user-images.githubusercontent.com/64391274/215766450-9621255f-b267-40f5-8812-d7c9f4ca25ad.png)

**Comment by rishabhpoddar** [comment]
Hey. Thank you so much for your PRs and helping us accelerate this feature. However, we are working on a slightly different way of doing search which makes it very difficult for us to use your existing PRs.

Therefore, I will have to close this and the associated PRs now.
