### ISSUE TITLE
Add the ability to search for users

### ISSUE THREAD

**Issue by nkshah2** [supertokens/dashboard#71]
## Summary of problem

Currently the only way to find a user is to use the user list, this is very problematic when the list of users is very large.

## Summary of solution

We allow users to be searchable using some piece of information associated with the user profile (email, phone etc).

### Terms

- Tags: Each piece of information that can be used to search a user is a tag. For example email, phone etc are all individual tags

### Overview of solution

 - We expose a new API from the core that allows searching for users. This API will receive a set of tags and values that should be used for searching
 - We expose an API from the core that returns a set of supported tags that can be used by the frontend. This allows search to be backwards compatible with different versions of the core. This means that the frontend must call this API before allowing search to be used _**[[[Should the entire page be in error state if this API fails? Or should only search be disabled?]]]**_

#### Core

- New API for list of tags
- Modify `/users GET` API to support query params for tags

#### Backend SDK
- New API for list of tags
- Modify `/users GET` API to forward query params sent by the frontend

#### Frontend

- New UI element for search on the user list page

**Comment by nkshah2** [comment]
## List of supported tags on launch

- email
- phone
- recipe (Auth mechanism)
- provider (optional)
- any (This means that the given information could be associated with any of the available tags)

**Comment by nkshah2** [comment]
## Frontend Flow Changes

1. On page load, fetch the list of tags supported by the core
2. When the user enters some information in the search box and hits enter (this is temporary, we can agree on another way of "submitting") call the search API assuming that the information is using the default tag (Read previous comment to know how to decide the default tag)
3. The user can then select a tag for the given information or enter another one. Either way the search should get triggered again (either with the new tag, or new information)
4. There should be a way to re-trigger the same query (maybe a submit button?)

**Comment by nkshah2** [comment]
## Frontend <-> BE

### General functioning of tags

When the frontend queries the backend SDK for user search it will send tags and values as query params. All tag based search logic should return values that **include** the given piece of information (for example email=some should return all users who's emails contain the text "some").

When multiple tags are used, the logic should assume an **AND** condition. For example ?email=some&phone=1 should return users with emails containing "some" **AND** with phone number containing "1"

When multiple values for the same tag are used, the logic should assume an **OR** condition.

You can have cases where both of the above cases apply simultaneously

```
/api/path?tag=value
```

The query can have multiple tags if the user is querying for multiple pieces of information

```
/api/path?tag1=value1&tag2=value2
```

A given tag can also have multiple values. In this case we will send the values in a semicolon separated string

```
/api/path?tag1=value1;value2;value3
```

#### Examples:

1. Searching all users with email including some text

```
/api/path?email=sometext
```

2. Searching all users with email including some text **AND** phone containing some number

```
/api/path?email=sometext&phone=123
```

3. Searching users with email containing one of multiple values

```
/api/path?email=text1;text2
```

4. Search all users email email containing some text and phone containing one of multiple values

```
/api/path?email=some&phone=123;789
```

5. Search all users with email and phone containing one of multiple values

```
/api/path?email=email1;email2&phone=123;789
```

**Comment by nkshah2** [comment]
## BE <-> Core

The backend SDK will simply be a proxy between the core and FE, no real logic needs to be implemented here

**Comment by nkshah2** [comment]
## Core

**ALL APIS NEED API KEY**
**ALL APIS NEED API KEY**
**ALL APIS NEED API KEY**
**ALL APIS NEED API KEY**

### New APIs

`/recipe/dashboard/tags GET`

This API returns a list of all supported tags that can be used to search with

Response:

```ts
{
    tags: string[]
}
```

If this API returns the `email` tag, that should be used as default by the frontend. If not then the first tag in the list should be considered default

`/recipe/dashboard/users/search GET`

Query: List of key value pairs (Refer to https://github.com/supertokens/dashboard/issues/71#issuecomment-1438172675 to see examples)

Response:

Same as `/users GET` API (already in the CDI)

NOTE: The logic of how multiple tag values and multiple tags in general is explained here 
 https://github.com/supertokens/dashboard/issues/71#issuecomment-1438172675

**Comment by nkshah2** [comment]
@jscyo ^

**Comment by DarkPhoenix2704** [comment]
Hey @nkshah2 
Can you check this PR. I have updated the users API for search last month. 

https://github.com/supertokens/supertokens-core/pull/561
https://github.com/supertokens/supertokens-plugin-interface/pull/51
https://github.com/supertokens/dashboard/issues/67

**Comment by nkshah2** [comment]
Hey @DarkPhoenix2704 

Yeah we used your PR as a foundation for our discussion but ended up deciding to go a slightly different approach. If you'd like you can go through the discussion on this issue and adjust your PR accordingly.

**Comment by nkshah2** [comment]
## Spec Changes
1. Update `/users GET` to account for new query params
2. Add `/recipe/dashboard/search/tags GET` API

**Comment by nkshah2** [comment]
@mufassirkazi

**Comment by jscyo** [comment]
Implementation changes:
- Search can ignore the pagination token
- A limit of 1000 on each subquery
- The search tags are: phone number, email, and provider
@rishabhpoddar @nkshah2
