### ISSUE TITLE
All users are being displayed as `johndoe@supertokens.com`

### ISSUE THREAD

**Issue by AshHeskes** [supertokens/dashboard#74]
When using the new version of `supertokens-node` `13.0.2` and the dashboard recipe. It's using the latest version of this app where all users email addresses are being converted to `johndoe@suertokens.com` and phone numbers are being obfuscated.

I have found the code that is the culprit, although I'm not sure why this has been added with no way to turn it off. 

https://github.com/supertokens/dashboard/blob/edf317fb2e19cbb9f06ff33fc9d40749a82521c2/src/ui/pages/usersList/UsersList.tsx#L112

**Comment by nkshah2** [comment]
Hi @AshHeskes 

Thanks for reporting this, we've released a fix for this (should automatically fetch the new version if you hard reload on your browser). Im closing this issue for now, feel free to re-open it if the issue persists
