### ISSUE TITLE
General UI Fixes

### ISSUE THREAD

**Issue by nkshah2** [supertokens/dashboard#78]
- [ ] All notifications for actions on the user details screen show up below the sign out button
- [x]  Shadow around the popup which appears when you hover the arrow next to the user in the users list screen has a wrong color
- [x] ~~No ability to multiselect and delete users yet?~~ This is something we dont want to support because dangerous operations should always involve some friction
- [x] The delete hover state is different in the hover dropdown text to the user in the user list screen
- [x] The grey container has a border radius
![Screenshot 2023-03-06 at 1 56 06 PM](https://user-images.githubusercontent.com/46087290/223056404-132e0f24-1ade-4f56-9d22-d43362fdcd7b.png)
- [x] The white container has a red shadow. This is not according to design.
![Screenshot 2023-03-06 at 1 56 57 PM](https://user-images.githubusercontent.com/46087290/223056639-828c242f-00d8-40a0-a817-83ee59d8acb1.png)
- [x] The supertokens logo has a weird blue background on hover
![Screenshot 2023-03-06 at 1 58 00 PM](https://user-images.githubusercontent.com/46087290/223056867-cf3cd669-b4cd-4ec6-8828-57f80bff7d21.png)
- [x] The cursor is auto when I hover here. It should be pointer
![Screenshot 2023-03-06 at 1 58 54 PM](https://user-images.githubusercontent.com/46087290/223057051-ff47d02f-f321-4d06-af9b-b3b25124da6c.png)
- [x] Can you please check the spacing of the individual elements? Even the icon sizes? It looks a little off from what I can see on design
![Screenshot 2023-03-06 at 2 01 01 PM](https://user-images.githubusercontent.com/46087290/223057504-d561d8db-e74e-4479-b2d0-9f8ae84fb7a7.png)
- [x] The change password screen input fields have default colors. Please check design. Also the first field should be autofocused.
![Screenshot 2023-03-06 at 2 04 43 PM](https://user-images.githubusercontent.com/46087290/223058271-170ae4f3-80bb-4719-86af-042f27696952.png)
- [x] The cancel button hover state is wrong
![Screenshot 2023-03-06 at 2 05 53 PM](https://user-images.githubusercontent.com/46087290/223058516-a204f5fa-2bf5-43fe-b3ff-979acd7450cf.png)
- [x] Same applies for change email popup. No default input field color and wrong cancel button hover state
![Screenshot 2023-03-06 at 2 10 22 PM](https://user-images.githubusercontent.com/46087290/223059526-4d3fa82c-1009-4979-8f16-6e898e63d728.png)
- [x] I don't like the delete forever deactivated state. 
![Screenshot 2023-03-06 at 2 11 47 PM](https://user-images.githubusercontent.com/46087290/223059825-6a1ab7f3-f58b-40d8-99b4-b6f007648c2e.png)
Instead please use the one from here: https://www.figma.com/file/Cy2eCZbmNZR3Debtl7wjo6/SuperTokens?node-id=870%3A36477&t=eZChHJdUyzEI4hRP-1
Image reference: 
![Screenshot 2023-03-06 at 2 13 03 PM](https://user-images.githubusercontent.com/46087290/223060056-cd79e766-593a-4dc2-aa2a-38996eceaac2.png)
- [x] Font weight is not proper for delete button in user details page
![Screenshot 2023-03
![Screenshot 2023-03-06 at 2 15 58 PM](https://user-images.githubusercontent.com/46087290/223060756-28e3855a-e5d4-41bd-b3a0-32cf3c9cd8d6.png)
-06 at 2 13 56 PM](https://user-images.githubusercontent.com/46087290/223060231-6b3a39dd-53a4-437f-b5f5-8ae6aa0b3d5e.png)
- [x] The cursor for copy button is supposed to be a pointer and not auto. This is applicable for all copy buttons
![Screenshot 2023-03-06 at 2 14 57 PM](https://user-images.githubusercontent.com/46087290/223060517-2a3c32e4-8243-4d2d-b5d7-9e54259bf4ec.png)
- [x] The cursor for info button is supposed to be a pointer and not auto. This is applicable for all info buttons
![Screenshot 2023-03-06 at 2 15 58 PM](https://user-images.githubusercontent.com/46087290/223060861-0bd40a8e-2656-46c5-a626-1f9d2072d336.png)
- [x] ~~The font is menlo~~ Ended up using Source Code Pro
![Screenshot 2023-03-06 at 2 17 26 PM](https://user-images.githubusercontent.com/46087290/223061091-951564c3-4dee-410f-a216-e9d253fbcf84.png)
- [x] All these red filled buttons have hovered states
![Screenshot 2023-03-06 at 2 17 58 PM](https://user-images.githubusercontent.com/46087290/223061241-f153095f-0739-437f-af28-85e018e5be67.png)
- [x] Font weight for cancel and sa
![Screenshot 2023-03-06 at 2 20 12 PM](https://user-images.githubusercontent.com/46087290/223061905-d2bcbe9c-df95-4c80-a531-88a9ff1e894a.png)
ve buttons is 500. Ideally the hover state for save button should be the default state
- [x] Why do all these white containers have a red shadow?
![Screenshot 2023-03-06 at 2 22 00 PM](https://user-images.githubusercontent.com/46087290/223062156-88b49e3a-ff8e-40a5-b054-21ae692646e7.png)

**Comment by mufassirkazi** [comment]
- [ ]  Shadow around the popup which appears when you hover the arrow next to the user in the users list screen has a wrong color
- [ ] No ability to multiselect and delete users yet?
- [ ] The delete hover state is different in the hover dropdown text to the user in the user list screen
- [ ] The grey container has a border radius
![Screenshot 2023-03-06 at 1 56 06 PM](https://user-images.githubusercontent.com/46087290/223056404-132e0f24-1ade-4f56-9d22-d43362fdcd7b.png)
- [ ] The white container has a red shadow. This is not according to design.
![Screenshot 2023-03-06 at 1 56 57 PM](https://user-images.githubusercontent.com/46087290/223056639-828c242f-00d8-40a0-a817-83ee59d8acb1.png)
- [ ] The supertokens logo has a weird blue background on hover
![Screenshot 2023-03-06 at 1 58 00 PM](https://user-images.githubusercontent.com/46087290/223056867-cf3cd669-b4cd-4ec6-8828-57f80bff7d21.png)
- [ ] The cursor is auto when I hover here. It should be pointer
![Screenshot 2023-03-06 at 1 58 54 PM](https://user-images.githubusercontent.com/46087290/223057051-ff47d02f-f321-4d06-af9b-b3b25124da6c.png)
- [ ] Can you please check the spacing of the individual elements? Even the icon sizes? It looks a little off from what I can see on design
![Screenshot 2023-03-06 at 2 01 01 PM](https://user-images.githubusercontent.com/46087290/223057504-d561d8db-e74e-4479-b2d0-9f8ae84fb7a7.png)
- [ ] The change password screen input fields have default colors. Please check design. Also the first field should be autofocused.
![Screenshot 2023-03-06 at 2 04 43 PM](https://user-images.githubusercontent.com/46087290/223058271-170ae4f3-80bb-4719-86af-042f27696952.png)
- [ ] The cancel button hover state is wrong
![Screenshot 2023-03-06 at 2 05 53 PM](https://user-images.githubusercontent.com/46087290/223058516-a204f5fa-2bf5-43fe-b3ff-979acd7450cf.png)
- [ ] Same applies for change email popup. No default input field color and wrong cancel button hover state
![Screenshot 2023-03-06 at 2 10 22 PM](https://user-images.githubusercontent.com/46087290/223059526-4d3fa82c-1009-4979-8f16-6e898e63d728.png)
- [ ] I don't like the delete forever deactivated state. 
![Screenshot 2023-03-06 at 2 11 47 PM](https://user-images.githubusercontent.com/46087290/223059825-6a1ab7f3-f58b-40d8-99b4-b6f007648c2e.png)
Instead please use the one from here: https://www.figma.com/file/Cy2eCZbmNZR3Debtl7wjo6/SuperTokens?node-id=870%3A36477&t=eZChHJdUyzEI4hRP-1
Image reference: 
![Screenshot 2023-03-06 at 2 13 03 PM](https://user-images.githubusercontent.com/46087290/223060056-cd79e766-593a-4dc2-aa2a-38996eceaac2.png)
- [ ] Font weight is not proper for delete button in user details page
![Screenshot 2023-03
![Screenshot 2023-03-06 at 2 15 58 PM](https://user-images.githubusercontent.com/46087290/223060756-28e3855a-e5d4-41bd-b3a0-32cf3c9cd8d6.png)
-06 at 2 13 56 PM](https://user-images.githubusercontent.com/46087290/223060231-6b3a39dd-53a4-437f-b5f5-8ae6aa0b3d5e.png)
- [ ] The cursor for copy button is supposed to be a pointer and not auto. This is applicable for all copy buttons
![Screenshot 2023-03-06 at 2 14 57 PM](https://user-images.githubusercontent.com/46087290/223060517-2a3c32e4-8243-4d2d-b5d7-9e54259bf4ec.png)
- [ ] The cursor for info button is supposed to be a pointer and not auto. This is applicable for all info buttons
![Screenshot 2023-03-06 at 2 15 58 PM](https://user-images.githubusercontent.com/46087290/223060861-0bd40a8e-2656-46c5-a626-1f9d2072d336.png)
- [ ] The font is menlo
![Screenshot 2023-03-06 at 2 17 26 PM](https://user-images.githubusercontent.com/46087290/223061091-951564c3-4dee-410f-a216-e9d253fbcf84.png)
- [ ] All these red filled buttons have hovered states
![Screenshot 2023-03-06 at 2 17 58 PM](https://user-images.githubusercontent.com/46087290/223061241-f153095f-0739-437f-af28-85e018e5be67.png)
- [ ] Font weight for cancel and sa
![Screenshot 2023-03-06 at 2 20 12 PM](https://user-images.githubusercontent.com/46087290/223061905-d2bcbe9c-df95-4c80-a531-88a9ff1e894a.png)
ve buttons is 500. Ideally the hover state for save button should be the default state
- [ ] Why do all these white containers have a red shadow?
![Screenshot 2023-03-06 at 2 22 00 PM](https://user-images.githubusercontent.com/46087290/223062156-88b49e3a-ff8e-40a5-b054-21ae692646e7.png)

**Comment by nkshah2** [comment]
- [ ] All notifications for actions on the user details screen show up below the sign out button
