### ISSUE TITLE
[Security] Google OAuth credentials in repo

### ISSUE THREAD

**Issue by mihaiblaga89** [supertokens/dashboard#80]
https://github.com/supertokens/dashboard/blob/4a88cf4d882c5c939b002f04c20797aeda7b4ab2/server/index.ts#LL71C7-L71C15
@nkshah2

**Comment by rishabhpoddar** [comment]
Hey. These are the demo credentials - also in our docs and all the demo apps. Therefore it's not for prod use and safe to use in the above repo.

Closing this issue.
